# Generated by Django 3.1.1 on 2020-10-16 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='rarity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('great_sword', 'Great Sword'), ('sword_&_shield', 'Sword & Shield'), ('dual_blades', 'Dual Blades'), ('long_sword', 'Long Sword'), ('hammer', 'Hammer'), ('hunting_horn', 'Hunting Horn'), ('lance', 'Lance'), ('gunlance', 'Gunlance'), ('switch_axe', 'Switch Axe'), ('charge_blade', 'Charge Blade'), ('insect_glaive', 'Insect Glaive'), ('bow', 'Bow'), ('light_bowgun', 'Light Bowgun'), ('heavy_bowgun', 'Heavy Bowgun')], max_length=30),
        ),
    ]
